### ISSUE TITLE
Active Membership Heading

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#1]
As a Member I want to see when my membership will be expiring so that I know when I have to pay
- [x] Update page UI to allow for banner
- [x] Upon page load check database for users expiration date
- [x] Update UI According to expiration date
- [x] Ensure all information is being created/stored in the database
- [x] Create technical and user documentation

**Comment by adobrusky** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/1?planning-poker) with Zenhub @taylor-runge @jjacobs10 @evanmielak
