### ISSUE TITLE
Track broken equipment

### ISSUE THREAD

**Issue by jjacobs10** [cseseniordesign/reservations#138]
As an admin, I want to be able to electronically track broken equipment.
- [x] Update database to include a row in tools table to mark equipment as broken
- [x] Add checkbox to mark equipment as broken
- [x] Prevent events from reserving broken equipment.
- [x] Show users tools cannot be reserved if they are broken
- [x] User and Technical Documentation

**Comment by hadleysusie** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/138?planning-poker) with Zenhub @adobrusky @evanmielak @jjacobs10 @zxzvipman
