### ISSUE TITLE
Member Sign-Up Captcha

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#2]
As an Admin I want users to have to complete a captcha when signing up so that mass signup attacks can be mitigated

- [x] Research Dependancies needed for api
- [x] Look into admin account for managing captcha portal
- [x] Implement captcha to website
- [x] Make captcha a requirement to finish sign up process
- [x] Create technical and user documentation

**Comment by taylor-runge** [comment]
- [] Research Dependancies needed for api
- [] Look into admin account for managing captcha portal
- [] Implement captcha to website
- [] Make captcha a requirement to finish sign up process

**Comment by taylor-runge** [comment]
- [ ] Research Dependancies needed for api
- [ ] Look into admin account for managing captcha portal
- [ ] Implement captcha to website
- [ ] Make captcha a requirement to finish sign up process
