### ISSUE TITLE
Membership Expiration Information on Website

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#3]
As an Admin, I want to be able to view membership expiration dates on the member table so that the memberships are tracked electronically.

- [ ] May need to just pull in the membership expiration date and display it on the "Manage Users" page assuming this data exists in the database. 
- [ ] If there is no "membership expiration date" data in the database we may need to make additional changes to populate that information.
- [ ] Create technical and user documentation

**Comment by taylor-runge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/3?planning-poker) with Zenhub @adobrusky @evanmielak @jjacobs10

**Comment by adobrusky** [comment]
Sponsors just need to get the expiration dates of users into the database otherwise this functionality is already present.
