### ISSUE TITLE
Sort Member Table

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#4]
As an Admin I want new tools to better sort all members so that I can more easily track and manipulate member data

Example for functionality: [LeBron James basketball reference](https://www.basketball-reference.com/players/j/jamesle01.html) The per game table sorting functions how I would expect ours to function, allowing to sort by either way (highest to lowest or lowest to highest).

- [x] Sort by name (Alphabetical)
- [x] Sort by email (Alphabetical)
- [x] Sort by expiration date (Time)

**Comment by taylor-runge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/4?planning-poker) with Zenhub @adobrusky @evanmielak @jjacobs10
