### ISSUE TITLE
Edit Multiple Expiration Dates

### ISSUE THREAD

**Issue by taylor-runge** [cseseniordesign/reservations#40]
As an Admin, I want to be able to edit the expiration dates of multiple users at once, so that in case of holidays I can push back the expiration date of many users at once instead of changing each one individually.
- [x] Add a button on the manage users page that when clicked will take the user to a new page.
- [x] Add a new page where the user can add or subtract days from all user's membership expiration dates.
- [x] Create user and technical documentation.

**Comment by adobrusky** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/40?planning-poker) with Zenhub @evanmielak @hadleysusie @jjacobs10 @taylor-runge @zxzvipman
