### ISSUE TITLE
Member Sign Up Information Update

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#5]
As an Admin I want new members to be able to provide more information upon signup so that I do not have to manually add the information later.

Add fields for:
   First Name
  Last Name
  Email Address 
  Relationship to the University (Dropdown menu)

- [x] Add additional UI for new information
- [x] Connect UI to existing backend
- [x] Ensure all information is being created/stored in the database
- [x] Create technical and user documentation

**Comment by taylor-runge** [comment]
- [ ] Add additional UI for new information
- [ ] Connect UI to existing backend
- [ ] Ensure all information is being created/stored in the database
