### ISSUE TITLE
Update "attending" checkbox to update database

### ISSUE THREAD

**Issue by adobrusky** [cseseniordesign/reservations#53]
As an admin, I want the tool permissions of a user to be updated when I check their attendance checkbox so that I do not have to manually update the user's tool permissions after they attend training.
- [x] Modify the database to store attended value for an event signup list
- [x] Modify the database to store the event id  where members got authorized for each tool
- [x] Create a submit button for the checkboxes form
- [x] add tool permissions for the reserved tools for that event when a member is checked
- [x] remove tool permissions for the reserved tools for that event when a member is unchecked
- [x] Create user and technical documentation

**Comment by adobrusky** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/53?planning-poker) with Zenhub @taylor-runge @hadleysusie @zxzvipman @jjacobs10

**Comment by taylor-runge** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/53?planning-poker) with Zenhub @adobrusky
