### ISSUE TITLE
Notify assigned trainer when assigned to event or when event details are modified

### ISSUE THREAD

**Issue by adobrusky** [cseseniordesign/reservations#55]
As a trainer, I want to be notified whenever I am assigned to an event or the event details change, so that I am always aware of the latest status of the event
- [x] Send an email to the trainer whenever an event is created with them assigned
- [x] Send an email to the trainer whenever the event is modified or deleted
- [x] Send an email to the trainer whenever they are removed from an event
- [x] Show events that the trainer is assigned to under the trainer's "My Events"
- [x] Create technical and user documentation

**Comment by hadleysusie** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/55?planning-poker) with Zenhub @adobrusky @jjacobs10 @taylor-runge @zxzvipman
