### ISSUE TITLE
Add alert center to sign up for notifications 

### ISSUE THREAD

**Issue by adobrusky** [cseseniordesign/reservations#56]
As a user, I want to have the option to be notified of the categories I choose from the alert center.

- [x] Add a UI element for members to join/leave the notified group for an alert category.  
- [x] When a member chooses the alert category they should be notified by email whenever the admin sends an email to that category. 
- [x] Create user and technical documentation

**Comment by hadleysusie** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/56?planning-poker) with Zenhub @adobrusky @jjacobs10 @taylor-runge @zxzvipman
