### ISSUE TITLE
Membership Expiration Reminder

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#6]
As a Member I want to be notified by email of my upcoming membership expiration so that I can be ready to pay the next time I go in.
- [x] Determine email template
- [x] #21
- [x] Send out emails to members found in routine
- [x] Ensure all information is being created/stored in the database
- [x] Create technical and user documentation

**Comment by taylor-runge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/6?planning-poker) with Zenhub @jjacobs10 @evanmielak @adobrusky
