### ISSUE TITLE
Search Member Table

### ISSUE THREAD

**Issue by evanmielak** [cseseniordesign/reservations#7]
As an Admin I want new tools to better search all members so that I can more easily track and manipulate member data.

- [x] Update the "Manage Users" page UI with search boxes to enter criteria to search the users by. There should be inputs to search by name, email, expiration date, and maybe tool authorizations (clarify this).
- [x] Update the "Manage Users" page UI with a search button to initiate the search
- [x] Create technical and user documentation

**Comment by taylor-runge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/7?planning-poker) with Zenhub @adobrusky @evanmielak @jjacobs10
