### ISSUE TITLE
Don't allow events to have a negative duration

### ISSUE THREAD

**Issue by jjacobs10** [cseseniordesign/reservations#89]
As a user, I don't want to be able to save events with a negative duration, so that bugs do not occur with showing trainings.
Example: event from 1/23/23 3 PM to 1/23/23 3 AM.

- [x] Add a check to prevent the user from saving events with a negative duration
- [x] Default the radio button from AM to PM
- [x] User and technical documentation

**Comment by hadleysusie** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nebraska-Innovation-Studio-63111060cd14b400139f8047/issues/cseseniordesign/reservations/89?planning-poker) with Zenhub @adobrusky @evanmielak @jjacobs10 @taylor-runge @zxzvipman
